# Generated by Django 5.1.3 on 2024-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('tour_package', models.CharField(choices=[('western-ghats-tour', 'Western Ghats Waterfall Tour'), ('north-east-expedition', 'North-East India Waterfall Expedition'), ('kerala-wellness-retreat', 'Kerala Waterfall & Wellness Retreat')], max_length=50, verbose_name='Tour Package')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('num_travelers', models.PositiveIntegerField(verbose_name='Number of Travelers')),
            ],
        ),
    ]
